Repository JuliaGraphs/MultilayerGraphs.jl, pull requests merged in 2023-01, with the labels that each got.

#55 General improvements to the user experience
  Project.toml
  README.md
  docs/src/API.md
  docs/src/index.md
  src/MultilayerGraphs.jl
  src/abstractmultilayergraph.jl
  src/abstractmultilayerugraph.jl
  src/graphs_extensions/metagraphs.jl
  src/halfedge.jl
  src/multilayerdigraph.jl
  src/multilayeredge.jl
  src/multilayergraph.jl
  src/subgraphs/abstractdescriptor.jl
  src/subgraphs/abstractsubgraph.jl
  src/subgraphs/interlayer.jl
  src/subgraphs/interlayerdescriptor.jl
  src/subgraphs/layer.jl
  src/subgraphs/layerdescriptor.jl
  src/traits.jl
  src/utilities.jl
  test/abstractmultilayerdigraph.jl
  test/interlayer.jl
  test/layer.jl
  test/runtests.jl
Labels: enhancement

#64 Update API, README and docs with minor fixes
  .vscode/settings.json
  README.md
  docs/make.jl
  docs/src/API.md
  docs/src/index.md
  src/abstractmultilayerdigraph.jl
  src/abstractmultilayergraph.jl
  src/abstractmultilayerugraph.jl
  src/multilayerdigraph.jl
  src/multilayeredge.jl
  src/multilayergraph.jl
  src/subgraphs/layer.jl
  test/runtests.jl
Labels: bug, documentation, enhancement

#65 Clean docs
  docs/src/index.md
Labels: documentation

#66 Rebase on "main" branch
  .vscode/settings.json
  Project.toml
  README.md
  docs/make.jl
  docs/src/API.md
  docs/src/index.md
  src/abstractmultilayerdigraph.jl
  src/abstractmultilayergraph.jl
  src/abstractmultilayerugraph.jl
  src/multilayerdigraph.jl
  src/multilayeredge.jl
  src/multilayergraph.jl
  src/subgraphs/layer.jl
  test/runtests.jl
Labels: bug, documentation, enhancement

#67 Set version to 1.1.1
  Project.toml
Labels: enhancement

#69 Add JOSS submission badge
  README.md
Labels: documentation

#70 Add JOSS submission badge
  README.md
Labels: documentation

#71 Update the README
  README.md
Labels: documentation

#72 Update README
  README.md
Labels: documentation

#74 Update README.md
  README.md
Labels: documentation

#75 Update README.md
  README.md
Labels: documentation

#76 Add v1.1 announcement posts in README and docs
  README.md
  docs/src/index.md
Labels: documentation

#77 Add v1.1 announcement posts to README and docs
  README.md
  docs/src/index.md
Labels: documentation

#80 Add example folder
  example/example.jl
  example/example.md
Labels: documentation

#81 Add example folder
  example/example.jl
Labels: documentation

#99 Update "Future Developments" section in README and docs
  README.md
  docs/src/index.md
Labels: documentation

#98 Update "Future Developments" section in README and docs
  README.md
  docs/src/index.md
Labels: documentation

#97 Update "Future Developments" section in README and docs
  README.md
  docs/src/index.md
Labels: documentation

#96 Update "Future Developments" section in README and docs
  README.md
  docs/src/index.md
Labels: documentation

#101 Fix bugs in README and example
  README.md
  example/example.jl
  example/example.md
Labels: documentation

#102 Fix bugs in README and example
  README.md
  example/example.jl
  example/example.md
Labels: documentation

#103 Fix bugs in README and example
  README.md
  example/example.jl
  example/example.md
Labels: documentation

#104 Fix bugs in README and example
  README.md
  example/example.jl
  example/example.md
Labels: documentation

#107 Traits based sub ecosystem & `NodeAlingnedEdgeColored(Di)Graph`
  Project.toml
  docs/Project.toml
  docs/make.jl
  docs/src/API.md
  docs/src/API_organized.md
  docs/src/index.md
  src/MultilayerGraphs.jl
  src/abstractmultilayergraph.jl
  src/analysis.jl
  src/directed.jl
  src/graphs_extensions/graphs.jl
  src/graphs_extensions/graphs_extensions.jl
  src/graphs_extensions/metagraphs.jl
  src/graphs_extensions/simplevaluegraphs.jl
  src/graphs_extensions/simpleweightedgraphs.jl
  src/multilayerdigraph.jl
  src/multilayergraph.jl
  src/special_multilayergraphs/node_aligned_edge_colored/abstract_node_aligned_edge_colored_graph.jl
  src/special_multilayergraphs/node_aligned_edge_colored/node_aligned_edge_colored_di_graph.jl
  src/special_multilayergraphs/node_aligned_edge_colored/node_aligned_edge_colored_graph.jl
  src/subgraphs/abstractsubgraph.jl
  src/subgraphs/layer.jl
  src/traits.jl
  src/undirected.jl
  src/utilities.jl
  test/node_aligned_edge_colored_graph.jl
  test/runtests.jl
Labels: enhancement

#112 Traits based sub ecosystem & `NodeAlingnedEdgeColored(Di)Graph`
  .github/workflows/CI.yml
  Project.toml
  docs/Project.toml
  docs/make.jl
  docs/src/API_organized.md
  docs/src/index.md
  src/MultilayerGraphs.jl
  src/abstractmultilayergraph.jl
  src/analysis.jl
  src/directed.jl
  src/graphs_extensions/graphs.jl
  src/graphs_extensions/graphs_extensions.jl
  src/graphs_extensions/metagraphs.jl
  src/graphs_extensions/simplevaluegraphs.jl
  src/graphs_extensions/simpleweightedgraphs.jl
  src/multilayerdigraph.jl
  src/multilayergraph.jl
  src/node.jl
  src/special_multilayergraphs/node_aligned_edge_colored/abstract_node_aligned_edge_colored_graph.jl
  src/special_multilayergraphs/node_aligned_edge_colored/node_aligned_edge_colored_di_graph.jl
  src/special_multilayergraphs/node_aligned_edge_colored/node_aligned_edge_colored_graph.jl
  src/subgraphs/abstractsubgraph.jl
  src/subgraphs/layer.jl
  src/traits.jl
  src/undirected.jl
  src/utilities.jl
  src/vertices/multilayervertex.jl
  test/node_aligned_edge_colored_graph.jl
  test/runtests.jl
Labels: enhancement

#110 Traits based sub ecosystem & `NodeAlingnedEdgeColored(Di)Graph`
  .github/workflows/CI.yml
  Project.toml
  docs/Project.toml
  docs/make.jl
  docs/src/API_organized.md
  docs/src/index.md
  src/MultilayerGraphs.jl
  src/abstractmultilayergraph.jl
  src/analysis.jl
  src/directed.jl
  src/graphs_extensions/graphs.jl
  src/graphs_extensions/graphs_extensions.jl
  src/graphs_extensions/metagraphs.jl
  src/graphs_extensions/simplevaluegraphs.jl
  src/graphs_extensions/simpleweightedgraphs.jl
  src/multilayerdigraph.jl
  src/multilayergraph.jl
  src/node.jl
  src/special_multilayergraphs/node_aligned_edge_colored/abstract_node_aligned_edge_colored_graph.jl
  src/special_multilayergraphs/node_aligned_edge_colored/node_aligned_edge_colored_di_graph.jl
  src/special_multilayergraphs/node_aligned_edge_colored/node_aligned_edge_colored_graph.jl
  src/subgraphs/abstractsubgraph.jl
  src/subgraphs/layer.jl
  src/traits.jl
  src/undirected.jl
  src/utilities.jl
  src/vertices/multilayervertex.jl
  test/node_aligned_edge_colored_graph.jl
  test/runtests.jl
Labels: enhancement

#111 Traits based sub ecosystem & `NodeAlingnedEdgeColored(Di)Graph`
  .github/workflows/CI.yml
  Project.toml
  docs/Project.toml
  docs/make.jl
  docs/src/API_organized.md
  docs/src/index.md
  src/MultilayerGraphs.jl
  src/abstractmultilayergraph.jl
  src/analysis.jl
  src/directed.jl
  src/graphs_extensions/graphs.jl
  src/graphs_extensions/graphs_extensions.jl
  src/graphs_extensions/metagraphs.jl
  src/graphs_extensions/simplevaluegraphs.jl
  src/graphs_extensions/simpleweightedgraphs.jl
  src/multilayerdigraph.jl
  src/multilayergraph.jl
  src/node.jl
  src/special_multilayergraphs/node_aligned_edge_colored/abstract_node_aligned_edge_colored_graph.jl
  src/special_multilayergraphs/node_aligned_edge_colored/node_aligned_edge_colored_di_graph.jl
  src/special_multilayergraphs/node_aligned_edge_colored/node_aligned_edge_colored_graph.jl
  src/subgraphs/abstractsubgraph.jl
  src/subgraphs/layer.jl
  src/traits.jl
  src/undirected.jl
  src/utilities.jl
  src/vertices/multilayervertex.jl
  test/node_aligned_edge_colored_graph.jl
  test/runtests.jl
Labels: enhancement

#114 Improve docs
  .github/workflows/CI.yml
  Project.toml
  README.md
  docs/Project.toml
  docs/make.jl
  docs/src/API.md
  docs/src/index.md
  example/example.jl
  example/example.md
  src/MultilayerGraphs.jl
  src/abstractmultilayergraph.jl
  src/analysis.jl
  src/directed.jl
  src/graphs_extensions/graphs.jl
  src/graphs_extensions/graphs_extensions.jl
  src/graphs_extensions/metagraphs.jl
  src/graphs_extensions/simplevaluegraphs.jl
  src/graphs_extensions/simpleweightedgraphs.jl
  src/multilayerdigraph.jl
  src/multilayergraph.jl
  src/node.jl
  src/special_multilayergraphs/node_aligned_edge_colored/abstract_node_aligned_edge_colored_graph.jl
  src/special_multilayergraphs/node_aligned_edge_colored/node_aligned_edge_colored_di_graph.jl
  src/special_multilayergraphs/node_aligned_edge_colored/node_aligned_edge_colored_graph.jl
  src/subgraphs/abstractsubgraph.jl
  src/subgraphs/layer.jl
  src/traits.jl
  src/undirected.jl
  src/utilities.jl
  test/directed.jl
  test/node_aligned_edge_colored_graph.jl
  test/runtests.jl
  test/undirected.jl
Labels: documentation

#115 Improve docs
  .github/workflows/CI.yml
  Project.toml
  docs/make.jl
  docs/src/API.md
  docs/src/index.md
  src/MultilayerGraphs.jl
  src/abstractmultilayergraph.jl
  src/directed.jl
  src/multilayerdigraph.jl
  src/multilayergraph.jl
  src/special_multilayergraphs/node_aligned_edge_colored/abstract_node_aligned_edge_colored_graph.jl
  src/special_multilayergraphs/node_aligned_edge_colored/node_aligned_edge_colored_di_graph.jl
  src/special_multilayergraphs/node_aligned_edge_colored/node_aligned_edge_colored_graph.jl
  src/undirected.jl
  src/vertices/multilayervertex.jl
  test/directed.jl
  test/runtests.jl
  test/undirected.jl
Labels: documentation

#117 Improve docs
  .github/workflows/CI.yml
  Project.toml
  docs/make.jl
  docs/src/API.md
  docs/src/index.md
  src/MultilayerGraphs.jl
  src/abstractmultilayergraph.jl
  src/directed.jl
  src/multilayerdigraph.jl
  src/multilayergraph.jl
  src/special_multilayergraphs/node_aligned_edge_colored/abstract_node_aligned_edge_colored_graph.jl
  src/special_multilayergraphs/node_aligned_edge_colored/node_aligned_edge_colored_di_graph.jl
  src/special_multilayergraphs/node_aligned_edge_colored/node_aligned_edge_colored_graph.jl
  src/undirected.jl
  src/vertices/multilayervertex.jl
  test/directed.jl
  test/runtests.jl
  test/undirected.jl
Labels: documentation

#119 Improve logo
  docs/src/assets/logo.png
Labels: documentation

#120 Improve logo
  docs/src/assets/logo.png
Labels: documentation

#121 Improve logo
  docs/src/assets/logo.png
Labels: documentation
